SET SERVEROUTPUT ON;

-- Switch to GLOBAL PDB
ALTER SESSION SET CONTAINER = eshop_global;

-- Check if user eshop_global_user exists
DECLARE
    user_exists NUMBER := 0;
BEGIN
    SELECT COUNT(*)
    INTO user_exists
    FROM dba_users
    WHERE username = 'ESHOP_GLOBAL_USER';

    IF user_exists = 0 THEN
        -- Create GLOBAL schema
        EXECUTE IMMEDIATE '
            CREATE USER eshop_global_user IDENTIFIED BY "GlobalUserPassword123!"
            ACCOUNT UNLOCK
        ';
        DBMS_OUTPUT.PUT_LINE('global_create_schema: User eshop_global_user was successfully created.');
    ELSE
        DBMS_OUTPUT.PUT_LINE('global_create_schema: User eshop_global_user already exists.');
    END IF;
END;
/

-- Check if role eshop_global_sys exists
DECLARE
    role_exists NUMBER := 0;
BEGIN
    SELECT COUNT(*)
    INTO role_exists
    FROM dba_roles
    WHERE role = 'ESHOP_GLOBAL_SYS';

    IF role_exists = 0 THEN
        -- Create role
        EXECUTE IMMEDIATE 'CREATE ROLE ESHOP_GLOBAL_SYS';
        DBMS_OUTPUT.PUT_LINE('global_create_schema: Role ESHOP_GLOBAL_SYS was successfully created.');
    ELSE
        DBMS_OUTPUT.PUT_LINE('global_create_schema: Role ESHOP_GLOBAL_SYS already exists.');
    END IF;
END;
/

-- Grant necessary privileges to the role
BEGIN
    EXECUTE IMMEDIATE 'GRANT CONNECT TO ESHOP_GLOBAL_SYS';
    EXECUTE IMMEDIATE 'GRANT RESOURCE TO ESHOP_GLOBAL_SYS';
    EXECUTE IMMEDIATE 'GRANT CREATE TABLE TO ESHOP_GLOBAL_SYS';
    EXECUTE IMMEDIATE 'GRANT CREATE VIEW TO ESHOP_GLOBAL_SYS';
    EXECUTE IMMEDIATE 'GRANT CREATE MATERIALIZED VIEW TO ESHOP_GLOBAL_SYS';
    EXECUTE IMMEDIATE 'GRANT CREATE SYNONYM TO ESHOP_GLOBAL_SYS';
    EXECUTE IMMEDIATE 'GRANT CREATE PROCEDURE TO ESHOP_GLOBAL_SYS';
    EXECUTE IMMEDIATE 'GRANT CREATE SEQUENCE TO ESHOP_GLOBAL_SYS';
    EXECUTE IMMEDIATE 'GRANT CREATE TRIGGER TO ESHOP_GLOBAL_SYS';
    EXECUTE IMMEDIATE 'GRANT CREATE TYPE TO ESHOP_GLOBAL_SYS';
    EXECUTE IMMEDIATE 'GRANT QUERY REWRITE TO ESHOP_GLOBAL_SYS';
    EXECUTE IMMEDIATE 'GRANT SELECT_CATALOG_ROLE TO ESHOP_GLOBAL_SYS';
    EXECUTE IMMEDIATE 'GRANT ALTER SESSION TO ESHOP_GLOBAL_SYS';
    EXECUTE IMMEDIATE 'GRANT SELECT ANY DICTIONARY TO ESHOP_GLOBAL_SYS';
    EXECUTE IMMEDIATE 'GRANT CREATE PUBLIC DATABASE LINK TO ESHOP_GLOBAL_SYS';
    EXECUTE IMMEDIATE 'GRANT CREATE PUBLIC SYNONYM TO ESHOP_GLOBAL_SYS';
END;
/

-- Grant the role and additional privileges to the user
BEGIN
    -- Grant the role to the user
    EXECUTE IMMEDIATE 'GRANT ESHOP_GLOBAL_SYS TO ESHOP_GLOBAL_USER';

    -- Grant additional privileges directly to the user
    EXECUTE IMMEDIATE 'GRANT CONNECT TO ESHOP_GLOBAL_USER';
    EXECUTE IMMEDIATE 'GRANT RESOURCE TO ESHOP_GLOBAL_USER';
    EXECUTE IMMEDIATE 'GRANT CREATE TABLE TO ESHOP_GLOBAL_USER';
    EXECUTE IMMEDIATE 'GRANT CREATE VIEW TO ESHOP_GLOBAL_USER';
    EXECUTE IMMEDIATE 'GRANT CREATE MATERIALIZED VIEW TO ESHOP_GLOBAL_USER';
    EXECUTE IMMEDIATE 'GRANT CREATE SYNONYM TO ESHOP_GLOBAL_USER';
    EXECUTE IMMEDIATE 'GRANT CREATE PROCEDURE TO ESHOP_GLOBAL_USER';
    EXECUTE IMMEDIATE 'GRANT CREATE SEQUENCE TO ESHOP_GLOBAL_USER';
    EXECUTE IMMEDIATE 'GRANT CREATE TRIGGER TO ESHOP_GLOBAL_USER';
    EXECUTE IMMEDIATE 'GRANT CREATE TYPE TO ESHOP_GLOBAL_USER';
    EXECUTE IMMEDIATE 'GRANT QUERY REWRITE TO ESHOP_GLOBAL_USER';
    EXECUTE IMMEDIATE 'GRANT SELECT_CATALOG_ROLE TO ESHOP_GLOBAL_USER';
    EXECUTE IMMEDIATE 'GRANT ALTER SESSION TO ESHOP_GLOBAL_USER';
    EXECUTE IMMEDIATE 'GRANT SELECT ANY DICTIONARY TO ESHOP_GLOBAL_USER';
    EXECUTE IMMEDIATE 'GRANT CREATE PUBLIC DATABASE LINK TO ESHOP_GLOBAL_USER';
    EXECUTE IMMEDIATE 'GRANT CREATE PUBLIC SYNONYM TO ESHOP_GLOBAL_USER';
    EXECUTE IMMEDIATE 'GRANT UNLIMITED TABLESPACE TO ESHOP_GLOBAL_USER';

    DBMS_OUTPUT.PUT_LINE('global_create_schema: Necessary privileges were granted to eshop_global_user.');
END;
/