SET SERVEROUTPUT ON;

-- Switch to MUNTENIA PDB
ALTER SESSION SET CONTAINER = eshop_muntenia;

-- Check if user eshop_muntenia_user exists
DECLARE
    user_exists NUMBER := 0;
BEGIN
    SELECT COUNT(*)
    INTO user_exists
    FROM dba_users
    WHERE username = 'ESHOP_MUNTENIA_USER';

    IF user_exists = 0 THEN
        -- Create MUNTENIA schema
        EXECUTE IMMEDIATE '
            CREATE USER eshop_muntenia_user IDENTIFIED BY "MunteniaUserPassword123!"
            ACCOUNT UNLOCK
        ';
        DBMS_OUTPUT.PUT_LINE('muntenia_create_schema: User eshop_muntenia_user was successfully created.');
    ELSE
        DBMS_OUTPUT.PUT_LINE('muntenia_create_schema: User eshop_muntenia_user already exists.');
    END IF;
END;
/ 

-- Grant the privileges to the user
BEGIN
    EXECUTE IMMEDIATE 'GRANT CONNECT TO ESHOP_MUNTENIA_USER';
    EXECUTE IMMEDIATE 'GRANT RESOURCE TO ESHOP_MUNTENIA_USER';
    EXECUTE IMMEDIATE 'GRANT CREATE TABLE TO ESHOP_MUNTENIA_USER';
    EXECUTE IMMEDIATE 'GRANT CREATE VIEW TO ESHOP_MUNTENIA_USER';
    EXECUTE IMMEDIATE 'GRANT CREATE MATERIALIZED VIEW TO ESHOP_MUNTENIA_USER';
    EXECUTE IMMEDIATE 'GRANT CREATE SYNONYM TO ESHOP_MUNTENIA_USER';
    EXECUTE IMMEDIATE 'GRANT CREATE PROCEDURE TO ESHOP_MUNTENIA_USER';
    EXECUTE IMMEDIATE 'GRANT CREATE SEQUENCE TO ESHOP_MUNTENIA_USER';
    EXECUTE IMMEDIATE 'GRANT CREATE TRIGGER TO ESHOP_MUNTENIA_USER';
    EXECUTE IMMEDIATE 'GRANT CREATE TYPE TO ESHOP_MUNTENIA_USER';
    EXECUTE IMMEDIATE 'GRANT QUERY REWRITE TO ESHOP_MUNTENIA_USER';
    EXECUTE IMMEDIATE 'GRANT SELECT_CATALOG_ROLE TO ESHOP_MUNTENIA_USER';
    EXECUTE IMMEDIATE 'GRANT ALTER SESSION TO ESHOP_MUNTENIA_USER';
    EXECUTE IMMEDIATE 'GRANT SELECT ANY DICTIONARY TO ESHOP_MUNTENIA_USER';
    EXECUTE IMMEDIATE 'GRANT CREATE PUBLIC DATABASE LINK TO ESHOP_MUNTENIA_USER';
    EXECUTE IMMEDIATE 'GRANT CREATE SESSION TO ESHOP_MUNTENIA_USER';
    EXECUTE IMMEDIATE 'GRANT CREATE PUBLIC SYNONYM TO ESHOP_MUNTENIA_USER';
    EXECUTE IMMEDIATE 'GRANT UNLIMITED TABLESPACE TO ESHOP_MUNTENIA_USER';
    EXECUTE IMMEDIATE 'GRANT ALTER ON IDNT_USERS TO eshop_muntenia_user';
    DBMS_OUTPUT.PUT_LINE('muntenia_create_schema: Necessary privileges were granted to eshop_muntenia_user.');
END;
/ 