SET SERVEROUTPUT ON;

-- Switch to ROMANIA PDB
ALTER SESSION SET CONTAINER = eshop_romania;

-- Check if user eshop_romania_user exists
DECLARE
    user_exists NUMBER := 0;
BEGIN
    SELECT COUNT(*)
    INTO user_exists
    FROM dba_users
    WHERE username = 'ESHOP_ROMANIA_USER';

    IF user_exists = 0 THEN
        -- Create ROMANIA schema
        EXECUTE IMMEDIATE '
            CREATE USER eshop_romania_user IDENTIFIED BY "RomaniaUserPassword123!"
            ACCOUNT UNLOCK
        ';
        DBMS_OUTPUT.PUT_LINE('romania_create_schema: User eshop_romania_user was successfully created.');
    ELSE
        DBMS_OUTPUT.PUT_LINE('romania_create_schema: User eshop_romania_user already exists.');
    END IF;
END;
/ 

-- Check if role eshop_romania_sys exists
DECLARE
    role_exists NUMBER := 0;
BEGIN
    SELECT COUNT(*)
    INTO role_exists
    FROM dba_roles
    WHERE role = 'ESHOP_ROMANIA_SYS';

    IF role_exists = 0 THEN
        -- Create role
        EXECUTE IMMEDIATE 'CREATE ROLE ESHOP_ROMANIA_SYS';
        DBMS_OUTPUT.PUT_LINE('romania_create_schema: Role ESHOP_ROMANIA_SYS was successfully created.');
    ELSE
        DBMS_OUTPUT.PUT_LINE('romania_create_schema: Role ESHOP_ROMANIA_SYS already exists.');
    END IF;
END;
/ 

-- Grant necessary privileges to the role
BEGIN
    EXECUTE IMMEDIATE 'GRANT CONNECT TO ESHOP_ROMANIA_SYS';
    EXECUTE IMMEDIATE 'GRANT RESOURCE TO ESHOP_ROMANIA_SYS';
    EXECUTE IMMEDIATE 'GRANT CREATE TABLE TO ESHOP_ROMANIA_SYS';
    EXECUTE IMMEDIATE 'GRANT CREATE VIEW TO ESHOP_ROMANIA_SYS';
    EXECUTE IMMEDIATE 'GRANT CREATE MATERIALIZED VIEW TO ESHOP_ROMANIA_SYS';
    EXECUTE IMMEDIATE 'GRANT CREATE SYNONYM TO ESHOP_ROMANIA_SYS';
    EXECUTE IMMEDIATE 'GRANT CREATE PROCEDURE TO ESHOP_ROMANIA_SYS';
    EXECUTE IMMEDIATE 'GRANT CREATE SEQUENCE TO ESHOP_ROMANIA_SYS';
    EXECUTE IMMEDIATE 'GRANT CREATE TRIGGER TO ESHOP_ROMANIA_SYS';
    EXECUTE IMMEDIATE 'GRANT CREATE TYPE TO ESHOP_ROMANIA_SYS';
    EXECUTE IMMEDIATE 'GRANT QUERY REWRITE TO ESHOP_ROMANIA_SYS';
    EXECUTE IMMEDIATE 'GRANT SELECT_CATALOG_ROLE TO ESHOP_ROMANIA_SYS';
    EXECUTE IMMEDIATE 'GRANT ALTER SESSION TO ESHOP_ROMANIA_SYS';
    EXECUTE IMMEDIATE 'GRANT SELECT ANY DICTIONARY TO ESHOP_ROMANIA_SYS';
    EXECUTE IMMEDIATE 'GRANT CREATE PUBLIC DATABASE LINK TO ESHOP_ROMANIA_SYS';
    EXECUTE IMMEDIATE 'GRANT CREATE PUBLIC SYNONYM TO ESHOP_ROMANIA_SYS';
END;
/ 

-- Grant the role and additional privileges to the user
BEGIN
    -- Grant the role to the user
    EXECUTE IMMEDIATE 'GRANT ESHOP_ROMANIA_SYS TO ESHOP_ROMANIA_USER';

    -- Grant additional privileges directly to the user
    EXECUTE IMMEDIATE 'GRANT CONNECT TO ESHOP_ROMANIA_USER';
    EXECUTE IMMEDIATE 'GRANT RESOURCE TO ESHOP_ROMANIA_USER';
    EXECUTE IMMEDIATE 'GRANT CREATE TABLE TO ESHOP_ROMANIA_USER';
    EXECUTE IMMEDIATE 'GRANT CREATE VIEW TO ESHOP_ROMANIA_USER';
    EXECUTE IMMEDIATE 'GRANT CREATE MATERIALIZED VIEW TO ESHOP_ROMANIA_USER';
    EXECUTE IMMEDIATE 'GRANT CREATE SYNONYM TO ESHOP_ROMANIA_USER';
    EXECUTE IMMEDIATE 'GRANT CREATE PROCEDURE TO ESHOP_ROMANIA_USER';
    EXECUTE IMMEDIATE 'GRANT CREATE SEQUENCE TO ESHOP_ROMANIA_USER';
    EXECUTE IMMEDIATE 'GRANT CREATE TRIGGER TO ESHOP_ROMANIA_USER';
    EXECUTE IMMEDIATE 'GRANT CREATE TYPE TO ESHOP_ROMANIA_USER';
    EXECUTE IMMEDIATE 'GRANT QUERY REWRITE TO ESHOP_ROMANIA_USER';
    EXECUTE IMMEDIATE 'GRANT SELECT_CATALOG_ROLE TO ESHOP_ROMANIA_USER';
    EXECUTE IMMEDIATE 'GRANT ALTER SESSION TO ESHOP_ROMANIA_USER';
    EXECUTE IMMEDIATE 'GRANT SELECT ANY DICTIONARY TO ESHOP_ROMANIA_USER';
    EXECUTE IMMEDIATE 'GRANT CREATE PUBLIC DATABASE LINK TO ESHOP_ROMANIA_USER';
    EXECUTE IMMEDIATE 'GRANT CREATE PUBLIC SYNONYM TO ESHOP_ROMANIA_USER';
    EXECUTE IMMEDIATE 'GRANT UNLIMITED TABLESPACE TO ESHOP_ROMANIA_USER';

    DBMS_OUTPUT.PUT_LINE('romania_create_schema: Necessary privileges were granted to eshop_romania_user.');
END;
/ 