SET SERVEROUTPUT ON;

-- Switch to MUNTENIA PDB
ALTER SESSION SET CONTAINER = eshop_muntenia;

-- Check if user eshop_muntenia_user exists
DECLARE
    user_exists NUMBER := 0;
BEGIN
    SELECT COUNT(*)
    INTO user_exists
    FROM dba_users
    WHERE username = 'ESHOP_MUNTENIA_USER';

    IF user_exists = 0 THEN
        -- Create MUNTENIA schema
        EXECUTE IMMEDIATE '
            CREATE USER eshop_muntenia_user IDENTIFIED BY "MunteniaUserPassword123!"
            ACCOUNT UNLOCK
        ';
        DBMS_OUTPUT.PUT_LINE('muntenia_create_schema: User eshop_muntenia_user was successfully created.');
    ELSE
        DBMS_OUTPUT.PUT_LINE('muntenia_create_schema: User eshop_muntenia_user already exists.');
    END IF;
END;
/ 

-- Check if role eshop_muntenia_sys exists
DECLARE
    role_exists NUMBER := 0;
BEGIN
    SELECT COUNT(*)
    INTO role_exists
    FROM dba_roles
    WHERE role = 'ESHOP_MUNTENIA_SYS';

    IF role_exists = 0 THEN
        -- Create role
        EXECUTE IMMEDIATE 'CREATE ROLE ESHOP_MUNTENIA_SYS';
        DBMS_OUTPUT.PUT_LINE('muntenia_create_schema: Role ESHOP_MUNTENIA_SYS was successfully created.');
    ELSE
        DBMS_OUTPUT.PUT_LINE('muntenia_create_schema: Role ESHOP_MUNTENIA_SYS already exists.');
    END IF;
END;
/ 

-- Grant necessary privileges to the role
BEGIN
    EXECUTE IMMEDIATE 'GRANT CONNECT TO ESHOP_MUNTENIA_SYS';
    EXECUTE IMMEDIATE 'GRANT RESOURCE TO ESHOP_MUNTENIA_SYS';
    EXECUTE IMMEDIATE 'GRANT CREATE TABLE TO ESHOP_MUNTENIA_SYS';
    EXECUTE IMMEDIATE 'GRANT CREATE VIEW TO ESHOP_MUNTENIA_SYS';
    EXECUTE IMMEDIATE 'GRANT CREATE MATERIALIZED VIEW TO ESHOP_MUNTENIA_SYS';
    EXECUTE IMMEDIATE 'GRANT CREATE SYNONYM TO ESHOP_MUNTENIA_SYS';
    EXECUTE IMMEDIATE 'GRANT CREATE PROCEDURE TO ESHOP_MUNTENIA_SYS';
    EXECUTE IMMEDIATE 'GRANT CREATE SEQUENCE TO ESHOP_MUNTENIA_SYS';
    EXECUTE IMMEDIATE 'GRANT CREATE TRIGGER TO ESHOP_MUNTENIA_SYS';
    EXECUTE IMMEDIATE 'GRANT CREATE TYPE TO ESHOP_MUNTENIA_SYS';
    EXECUTE IMMEDIATE 'GRANT QUERY REWRITE TO ESHOP_MUNTENIA_SYS';
    EXECUTE IMMEDIATE 'GRANT SELECT_CATALOG_ROLE TO ESHOP_MUNTENIA_SYS';
    EXECUTE IMMEDIATE 'GRANT ALTER SESSION TO ESHOP_MUNTENIA_SYS';
    EXECUTE IMMEDIATE 'GRANT SELECT ANY DICTIONARY TO ESHOP_MUNTENIA_SYS';
    EXECUTE IMMEDIATE 'GRANT CREATE PUBLIC DATABASE LINK TO ESHOP_MUNTENIA_SYS';
    EXECUTE IMMEDIATE 'GRANT CREATE PUBLIC SYNONYM TO ESHOP_MUNTENIA_SYS';
    EXECUTE IMMEDIATE 'GRANT UNLIMITED TABLESPACE TO ESHOP_MUNTENIA_SYS';
END;
/ 

-- Grant the role and additional privileges to the user
BEGIN
    -- Grant the role to the user
    EXECUTE IMMEDIATE 'GRANT ESHOP_MUNTENIA_SYS TO ESHOP_MUNTENIA_USER';

    -- Grant additional privileges directly to the user
    EXECUTE IMMEDIATE 'GRANT CONNECT TO ESHOP_MUNTENIA_USER';
    EXECUTE IMMEDIATE 'GRANT RESOURCE TO ESHOP_MUNTENIA_USER';
    EXECUTE IMMEDIATE 'GRANT CREATE TABLE TO ESHOP_MUNTENIA_USER';
    EXECUTE IMMEDIATE 'GRANT CREATE VIEW TO ESHOP_MUNTENIA_USER';
    EXECUTE IMMEDIATE 'GRANT CREATE MATERIALIZED VIEW TO ESHOP_MUNTENIA_USER';
    EXECUTE IMMEDIATE 'GRANT CREATE SYNONYM TO ESHOP_MUNTENIA_USER';
    EXECUTE IMMEDIATE 'GRANT CREATE PROCEDURE TO ESHOP_MUNTENIA_USER';
    EXECUTE IMMEDIATE 'GRANT CREATE SEQUENCE TO ESHOP_MUNTENIA_USER';
    EXECUTE IMMEDIATE 'GRANT CREATE TRIGGER TO ESHOP_MUNTENIA_USER';
    EXECUTE IMMEDIATE 'GRANT CREATE TYPE TO ESHOP_MUNTENIA_USER';
    EXECUTE IMMEDIATE 'GRANT QUERY REWRITE TO ESHOP_MUNTENIA_USER';
    EXECUTE IMMEDIATE 'GRANT SELECT_CATALOG_ROLE TO ESHOP_MUNTENIA_USER';
    EXECUTE IMMEDIATE 'GRANT ALTER SESSION TO ESHOP_MUNTENIA_USER';
    EXECUTE IMMEDIATE 'GRANT SELECT ANY DICTIONARY TO ESHOP_MUNTENIA_USER';
    EXECUTE IMMEDIATE 'GRANT CREATE PUBLIC DATABASE LINK TO ESHOP_MUNTENIA_USER';
    EXECUTE IMMEDIATE 'GRANT CREATE PUBLIC SYNONYM TO ESHOP_MUNTENIA_USER';
    EXECUTE IMMEDIATE 'GRANT UNLIMITED TABLESPACE TO ESHOP_MUNTENIA_USER';

    DBMS_OUTPUT.PUT_LINE('muntenia_create_schema: Necessary privileges were granted to eshop_muntenia_user.');
END;
/ 