WHENEVER SQLERROR EXIT SQL.SQLCODE;

-- Check if the ESHOP_ROMANIA PDB already exists
DECLARE
  pdb_exists NUMBER := 0;
BEGIN
  SELECT COUNT(*) INTO pdb_exists FROM V$PDBS WHERE NAME = 'ESHOP_ROMANIA';

  IF pdb_exists = 0 THEN
    -- Create the ESHOP_ROMANIA PDB
    EXECUTE IMMEDIATE 'CREATE PLUGGABLE DATABASE ESHOP_ROMANIA ADMIN USER romania_admin IDENTIFIED BY "RomaniaAdminPassword123!" FILE_NAME_CONVERT = (''/opt/oracle/oradata/ORCLCDB/pdbseed'', ''/opt/oracle/oradata/ROMANIACDB/ESHOP_ROMANIA'')';
    EXECUTE IMMEDIATE 'ALTER PLUGGABLE DATABASE ESHOP_ROMANIA OPEN';
  END IF;
END;
/ 
