WHENEVER SQLERROR EXIT SQL.SQLCODE;

-- Check if the ESHOP_MUNTENIA PDB already exists
DECLARE
  pdb_exists NUMBER := 0;
BEGIN
  SELECT COUNT(*) INTO pdb_exists FROM V$PDBS WHERE NAME = 'ESHOP_MUNTENIA';

  IF pdb_exists = 0 THEN
    -- Create the ESHOP_MUNTENIA PDB
    EXECUTE IMMEDIATE 'CREATE PLUGGABLE DATABASE ESHOP_MUNTENIA ADMIN USER muntenia_admin IDENTIFIED BY "MunteniaAdminPassword123!" FILE_NAME_CONVERT = (''/opt/oracle/oradata/ORCLCDB/pdbseed'', ''/opt/oracle/oradata/MUNTENIACDB/ESHOP_MUNTENIA'')';
    EXECUTE IMMEDIATE 'ALTER PLUGGABLE DATABASE ESHOP_MUNTENIA OPEN';
  END IF;
END;
/