WHENEVER SQLERROR EXIT SQL.SQLCODE;

-- Check if the ESHOP_GLOBAL PDB already exists
DECLARE
  pdb_exists NUMBER := 0;
BEGIN
  SELECT COUNT(*) INTO pdb_exists FROM V$PDBS WHERE NAME = 'ESHOP_GLOBAL';

  IF pdb_exists = 0 THEN
    -- Create the ESHOP_GLOBAL PDB
    EXECUTE IMMEDIATE 'CREATE PLUGGABLE DATABASE ESHOP_GLOBAL ADMIN USER global_admin IDENTIFIED BY "GlobalAdminPassword123!" FILE_NAME_CONVERT = (''/opt/oracle/oradata/ORCLCDB/pdbseed'', ''/opt/oracle/oradata/GLOBALCDB/ESHOP_GLOBAL'')';
    EXECUTE IMMEDIATE 'ALTER PLUGGABLE DATABASE ESHOP_GLOBAL OPEN';
  END IF;
END;
/
